// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

public class OpenAI_ResponseStream extends UserAction<java.lang.Void>
{
	/** @deprecated use responseStream.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __responseStream;
	private final example.proxies.ResponseStream responseStream;
	private final java.lang.String inputMessage;
	private final java.lang.String modelName;
	private final java.lang.String apiKey;
	private final java.lang.String endpoint;
	private final example.proxies.ENUM_OpenAiType apiType;

	public OpenAI_ResponseStream(
		IContext context,
		IMendixObject _responseStream,
		java.lang.String _inputMessage,
		java.lang.String _modelName,
		java.lang.String _apiKey,
		java.lang.String _endpoint,
		java.lang.String _apiType
	)
	{
		super(context);
		this.__responseStream = _responseStream;
		this.responseStream = _responseStream == null ? null : example.proxies.ResponseStream.initialize(getContext(), _responseStream);
		this.inputMessage = _inputMessage;
		this.modelName = _modelName;
		this.apiKey = _apiKey;
		this.endpoint = _endpoint;
		this.apiType = _apiType == null ? null : example.proxies.ENUM_OpenAiType.valueOf(_apiType);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ObjectMapper mapper = new ObjectMapper();
		
		URL url = new URL(endpoint);
		HttpURLConnection conn = (HttpURLConnection) url.openConnection();
		
		conn.setRequestMethod("POST");
		conn.setRequestProperty("Content-Type", "application/json");
		conn.setRequestProperty("Authorization", "Bearer " + apiKey);
		conn.setRequestProperty("Accept", "text/event-stream");
		if ("AzureOpenAI".equals(apiType)) {
			conn.setRequestProperty("api-key", apiKey);
		} else {
			conn.setRequestProperty("Authorization", "Bearer " + apiKey);
		}
		conn.setDoOutput(true);
		conn.setConnectTimeout(30000);
		conn.setReadTimeout(300000);
		
		// Build JSON body
		String body =
		"{"
		+ "\"model\":\"" + modelName + "\","
		+ "\"messages\":[{\"role\":\"user\",\"content\":\"" + inputMessage.replace("\"","\\\"") + "\"}],"
		+ "\"stream\":true"
		+ "}";
		
		// Send request
		OutputStream os = conn.getOutputStream();
		os.write(body.getBytes("UTF-8"));
		os.close();
		
		// Prepare reader
		BufferedReader reader = new BufferedReader(
				new InputStreamReader(conn.getInputStream(), "UTF-8")
		);

		String line;
		String output = "";
		
		// Initialize Mendix field
		responseStream.setOutputText("");

		while ((line = reader.readLine()) != null) {

			if (!line.startsWith("data:")) {
				continue;
			}

			String json = line.substring(5).trim();

			if ("[DONE]".equals(json)) {
				break;
			}
			
			try {

				JsonNode parsed = mapper.readTree(json);

				JsonNode deltaNode = parsed
						.path("choices")
						.get(0)
						.path("delta")
						.path("content");

				if (!deltaNode.isMissingNode()) {

					String delta = deltaNode.asText();

					output += delta;

					responseStream.setOutputText(output);

					com.mendix.core.Core.commit(getContext(), responseStream.getMendixObject());
				}

			} catch (Exception e) {
				// Ignore errenous partial chunks
			}
		}
		
		reader.close();
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OpenAI_ResponseStream";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
