// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Uses the OpenAI proxy to allow customised JSON to be sent to the AI. To stream output, ensure the stream parameter is added to the JSON.
 * @param {MxObject} outputStream
 * @param {string} inputJSON
 * @param {boolean} showProgressBar
 * @param {string} focusClass
 * @param {Big} commitInterval - How often output stream object is committed (ms). Default is 50ms
 * @returns {Promise.<boolean>}
 */
export async function JS_OpenAI_ProxyStreamFromJson(outputStream, inputJSON, showProgressBar, focusClass, commitInterval) {
	// BEGIN USER CODE
	let idProg;
	const targetNode = focusClass ? document.querySelector(focusClass) : null;

	// Default interval to 50 if not provided
	commitInterval = commitInterval > 0 ? commitInterval : 50;

	if (showProgressBar) idProg = mx.ui.showProgress("Thinking...", false);
	// Call Mendix streaming proxy
	const response = await fetch("/ai-stream/", {
		method: "POST",
		headers: {
			"Content-Type": "application/json"
		},
		body: inputJSON
	});

	// Error check
	if (!response.ok || !response.body) {
		const errorText = await response.text().catch(() => "");
		if (showProgressBar) mx.ui.hideProgress(Number(idProg));
		console.error("Stream request failed", errorText);
		return false;
	}

	const reader = response.body.getReader();
	const decoder = new TextDecoder("utf-8");
	let streamComplete = false;

	if (showProgressBar) {
		mx.ui.hideProgress(Number(idProg));
	}

	// Initialize Mendix object
	outputStream.set("OutputText", "");

	let buffer = ""; // Helps reduce chunk parse error
	let localText = "";      // Local accumulator
    let commitPending = false;

    // Commit on a throttle
	// Commit so Mendix UI updates
    const scheduleCommit = () => {
        if (commitPending) return;
        commitPending = true;
        setTimeout(() => {
            outputStream.set("OutputText", localText);
            mx.data.commit({
                mxobj: outputStream,
                callback: () => { commitPending = false; },
				error: () => { commitPending = false; }
            });
	    	// Scroll to focused class
            if (targetNode) targetNode.scrollIntoView({ behavior: "instant" });
			}, commitInterval); // Commit interval in ms
    };

	while (!streamComplete) {
		const { value, done } = await reader.read();
		if (done) {
			streamComplete = true;
			break;
		}

		if (!value) continue;
		// Append new bytes to the carry-over buffer
		buffer += decoder.decode(value, { stream: true });

		// Splits into new lines
		const lines = buffer.split("\n");
		buffer = lines.pop(); 

		for (const line of lines) {
			if (!line.trim().startsWith("data:")) continue;

			const json = line.replace(/^data:\s*/, "").trim();

			if (json === "[DONE]") {
            	streamComplete = true;
            	break;
        	}

			try {
				const parsed = JSON.parse(json);
				const delta = parsed.choices?.[0]?.delta?.content;

				if (delta) {
					localText += delta;
					scheduleCommit();
				}
			} catch (e) {
				console.warn("Chunk parse error", e);
			}
		}
	}
	// Flush decorder
	buffer += decoder.decode();
	console.log("Streaming complete");

	return true;
	// END USER CODE
}
