// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} outputStream
 * @param {string} inputMessage
 * @param {string} modelName
 * @param {boolean} showProgressBar
 * @param {string} focusClass
 * @returns {Promise.<boolean>}
 */
export async function JS_OpenAI_ProxyStream(outputStream, inputMessage, modelName, showProgressBar, focusClass) {
	// BEGIN USER CODE
	let idProg;
	const targetNode = focusClass ? document.querySelector(focusClass) : null;

	if (showProgressBar) {
		idProg = mx.ui.showProgress("Thinking...", false);
	}
	// Call Mendix streaming proxy
	const response = await fetch("/ai-stream/", {
		method: "POST",
		headers: {
			"Content-Type": "application/json"
		},
		body: JSON.stringify({
			model: modelName,
			messages: [
				{ role: "user", content: inputMessage }
			],
			stream: true
		})
	});

	// Error check
	if (!response.ok || !response.body) {
		const errorText = await response.text().catch(() => "");
		console.error("Stream request failed", errorText);
		return false;
	}

	const reader = response.body.getReader();
	const decoder = new TextDecoder("utf-8");
	let streamComplete = false;

	if (showProgressBar) {
		mx.ui.hideProgress(Number(idProg));
	}

	// Initialize Mendix object
	outputStream.set("OutputText", "");

	let buffer = ""; // Helps reduce chunk parse error

	while (!streamComplete) {
		const { value, done } = await reader.read();
		if (done) {
			streamComplete = true;
			break;
		}

		if (!value) continue;
		// Append new bytes to the carry-over buffer
		buffer += decoder.decode(value, { stream: true });

		// Splits into new lines
		const lines = buffer.split("\n");
		buffer = lines.pop(); 

		for (const line of lines) {
			if (!line.trim().startsWith("data:")) continue;

			const json = line.replace(/^data:\s*/, "").trim();

			if (json === "[DONE]") {
            	streamComplete = true;
            	break;
        	}

			try {
				const parsed = JSON.parse(json);
				const delta = parsed.choices?.[0]?.delta?.content;

				if (delta) {
					const current = outputStream.get("OutputText") || "";
					outputStream.set("OutputText", current + delta);
					if (targetNode) {
                        // Scroll to focused class
                        targetNode.scrollIntoView({ behavior: 'instant' });
                    }

				}

			} catch (e) {
				console.warn("Chunk parse error", e);
			}
		}

		// Commit so Mendix UI updates
		await new Promise(resolve => {
			mx.data.commit({
				mxobj: outputStream,
				callback: resolve
			});
		});
	}
	// Flush decorder
	buffer += decoder.decode();
	console.log("Streaming complete");

	return true;
	// END USER CODE
}