// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ex.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import ex.actions.handlers.OpenAIStreamHandler;

public class ASU_OpenAI_StreamProxy extends UserAction<java.lang.Void>
{
	private final java.lang.String apiKey;
	private final java.lang.String modelName;
	private final java.lang.String endpoint;

	public ASU_OpenAI_StreamProxy(
		IContext context,
		java.lang.String _apiKey,
		java.lang.String _modelName,
		java.lang.String _endpoint
	)
	{
		super(context);
		this.apiKey = _apiKey;
		this.modelName = _modelName;
		this.endpoint = _endpoint;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Create and register OpenAI proxy handler to send requests to
        OpenAIStreamHandler handler = new OpenAIStreamHandler(this.apiKey, this.endpoint, this.modelName);
            
        // Register handler
        Core.addRequestHandler("ai/stream/", handler);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ASU_OpenAI_StreamProxy";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
