// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package openaioutputstream.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import openaioutputstream.actions.handlers.OpenAIStreamHandler;
import com.mendix.webui.CustomJavaAction;

/**
 * Sets up an OpenAI proxy which can be used for streaming responses to user. 
 * This stops api keys being exposed via nanoflows.
 */
public class ASU_OpenAI_StreamProxy extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String apiKey;
	private java.lang.String endpoint;
	private openaioutputstream.proxies.ENUM_OpenAI_Type apiType;

	public ASU_OpenAI_StreamProxy(IContext context, java.lang.String apiKey, java.lang.String endpoint, java.lang.String apiType)
	{
		super(context);
		this.apiKey = apiKey;
		this.endpoint = endpoint;
		this.apiType = apiType == null ? null : openaioutputstream.proxies.ENUM_OpenAI_Type.valueOf(apiType);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Create and register OpenAI proxy handler to send requests to
        OpenAIStreamHandler handler = new OpenAIStreamHandler(this.apiKey, this.endpoint, this.apiType);
            
        // Register handler
        Core.addRequestHandler("ai-stream/", handler);
		if (handler == null) return false;
		else return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ASU_OpenAI_StreamProxy";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
